/obj/structure/closet/paramedic/populate_contents()
	new	/obj/item/clothing/under/rank/medical/paramedic/skirt(src)
	new	/obj/item/clothing/under/rank/medical/paramedic/skirt(src)
	new	/obj/item/clothing/head/beret/med/paramedic(src)
	new	/obj/item/clothing/head/beret/med/paramedic(src)
	new /obj/item/clothing/head/soft/paramed(src)
	new /obj/item/clothing/head/soft/paramed(src)
	..()
